package one.dqu.additionaladditions.feature.suspicious_dye.glint;

import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.renderpearl.api.textures.FilterMode;
import com.mojang.renderpearl.api.textures.GpuSampler;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.geom.builders.UVPair;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.client.renderer.feature.ItemFeatureRenderer;
import net.minecraft.client.renderer.rendertype.LayeringTransform;
import net.minecraft.client.renderer.rendertype.RenderSetup;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.rendertype.TextureTransform;
import net.minecraft.client.renderer.texture.TextureAtlas;
import net.minecraft.client.resources.model.geometry.BakedQuad;
import net.minecraft.core.Direction;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.DyeColor;
import one.dqu.additionaladditions.AdditionalAdditions;
import org.jetbrains.annotations.Nullable;
import org.joml.Matrix3f;
import org.joml.Matrix4f;
import org.joml.Vector3f;
import org.joml.Vector3fc;

import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Colored glint render types using the tinted textures generated by {@link GlintResourceGenerator}.
 */
@Environment(EnvType.CLIENT)
public class GlintRenderTypes {
    private static final Supplier<GpuSampler> GLINT_SAMPLER = () -> RenderSystem.getSamplerCache().getRepeat(FilterMode.LINEAR);

    private static final Map<Key, RenderType> CACHE = new HashMap<>();
    private static @Nullable Map<RenderType, Function<DyeColor, RenderType>> inlineItemTypes;
    private static @Nullable Map<RenderType, String> overlayItemTypes;

    public static Identifier itemTexture(DyeColor color) {
        return Identifier.fromNamespaceAndPath(AdditionalAdditions.NAMESPACE, "textures/util/enchanted_item_glint_" + color.getName().toLowerCase(Locale.ROOT) + ".png");
    }

    public static Identifier entityTexture(DyeColor color) {
        return Identifier.fromNamespaceAndPath(AdditionalAdditions.NAMESPACE, "textures/util/enchanted_entity_glint_" + color.getName().toLowerCase(Locale.ROOT) + ".png");
    }

    // translucent items keep the inline glint since the vanilla glint pipeline has no oit pipelines
    public static RenderType item(RenderType original, DyeColor color) {
        if (inlineItemTypes == null) {
            inlineItemTypes = new IdentityHashMap<>();
            for (Identifier atlas : new Identifier[]{TextureAtlas.LOCATION_ITEMS, TextureAtlas.LOCATION_BLOCKS}) {
                inlineItemTypes.put(RenderTypes.itemTranslucentGlint(atlas), c -> itemTranslucentGlint(atlas, c));
                inlineItemTypes.put(RenderTypes.itemTranslucentGlintSpecial(atlas), c -> itemTranslucentGlintSpecial(atlas, c));
            }
        }
        Function<DyeColor, RenderType> factory = inlineItemTypes.get(original);
        return factory != null ? factory.apply(color) : original;
    }

    // glint is drawn as a separate render type using the vanilla glint pipeline for compatibility with shader packs / iris
    // iris ignores the glint texture of inline glint render types and always uses the vanilla one
    public static @Nullable RenderType itemOverlay(RenderType original, DyeColor color) {
        if (overlayItemTypes == null) {
            overlayItemTypes = new IdentityHashMap<>();
            for (Identifier atlas : new Identifier[]{TextureAtlas.LOCATION_ITEMS, TextureAtlas.LOCATION_BLOCKS}) {
                overlayItemTypes.put(RenderTypes.itemCutoutGlint(atlas), "item_glint_" + overlayItemTypes.size());
                overlayItemTypes.put(RenderTypes.itemCutoutGlintSpecial(atlas), "item_glint_" + overlayItemTypes.size());
            }
        }
        String name = overlayItemTypes.get(original);
        if (name == null) {
            return null;
        }
        return CACHE.computeIfAbsent(new Key(name, null, color), key -> RenderType.create(name,
                RenderSetup.builder(RenderPipelines.GLINT)
                        .withTexture("Sampler0", itemTexture(color), GLINT_SAMPLER)
                        .setTextureTransform(TextureTransform.GLINT_TEXTURING)
                        .createRenderSetup()));
    }

    // based on VertexConsumer#putBakedQuad, VertexConsumer#putBakedQuadWithGlint and SheetedDecalTextureGenerator#setSheetedDecalUv
    // the glint pipeline only has position and uv, so the sheeted decal uv is written to uv0 instead of uv3
    public static void putItemOverlayQuad(VertexConsumer consumer, PoseStack.Pose pose, BakedQuad quad, PoseStack.@Nullable Pose sheetedDecalPose) {
        Vector3fc normalVec = quad.direction().getUnitVec3f();
        Matrix4f matrix = pose.pose();
        Vector3f normal = pose.transformNormal(normalVec, new Vector3f());
        Matrix4f cameraInversePose = sheetedDecalPose != null ? new Matrix4f(sheetedDecalPose.pose()).invert() : null;
        Matrix3f normalInversePose = sheetedDecalPose != null ? new Matrix3f(sheetedDecalPose.normal()).invert() : null;

        for (int vertex = 0; vertex < 4; vertex++) {
            Vector3fc position = quad.position(vertex);
            long packedUv = quad.packedUV(vertex);
            Vector3f pos = matrix.transformPosition(position, new Vector3f());
            float u = UVPair.unpackU(packedUv);
            float v = UVPair.unpackV(packedUv);
            if (cameraInversePose != null) {
                Vector3f transformedNormal = normalInversePose.transform(normal.x(), normal.y(), normal.z(), new Vector3f());
                Direction direction = Direction.getApproximateNearest(transformedNormal.x(), transformedNormal.y(), transformedNormal.z());
                Vector3f worldPos = cameraInversePose.transformPosition(pos.x, pos.y, pos.z, new Vector3f());
                worldPos.rotateY((float) Math.PI);
                worldPos.rotateX((float) (-Math.PI / 2));
                worldPos.rotate(direction.getRotation());
                u = -worldPos.x() * ItemFeatureRenderer.SPECIAL_FOIL_TEXTURE_SCALE;
                v = -worldPos.y() * ItemFeatureRenderer.SPECIAL_FOIL_TEXTURE_SCALE;
            }
            consumer.addVertex(pos.x(), pos.y(), pos.z()).setUv(u, v);
        }
    }

    public static RenderType itemTranslucentGlint(Identifier texture, DyeColor color) {
        return CACHE.computeIfAbsent(new Key("item_translucent_glint", texture, color), key -> RenderType.create("item_translucent_glint",
                RenderSetup.builder(RenderPipelines.ITEM_TRANSLUCENT_GLINT)
                        .setOitPipelines(RenderPipelines.OIT_ITEM_GLINT)
                        .withTexture("Sampler0", texture)
                        .withTexture("GlintSampler", inlineItemTexture(color), GLINT_SAMPLER)
                        .setTextureTransform(TextureTransform.GLINT_TEXTURING)
                        .useLightmap()
                        .useOverlay()
                        .affectsCrumbling()
                        .sortOnUpload()
                        .setOutline(RenderSetup.OutlineProperty.AFFECTS_OUTLINE)
                        .createRenderSetup()));
    }

    public static RenderType itemTranslucentGlintSpecial(Identifier texture, DyeColor color) {
        return CACHE.computeIfAbsent(new Key("item_translucent_glint_special", texture, color), key -> RenderType.create("item_translucent_glint_special",
                RenderSetup.builder(RenderPipelines.ITEM_TRANSLUCENT_GLINT_SPECIAL)
                        .setOitPipelines(RenderPipelines.OIT_ITEM_GLINT_SPECIAL)
                        .withTexture("Sampler0", texture)
                        .withTexture("GlintSampler", inlineItemTexture(color), GLINT_SAMPLER)
                        .setTextureTransform(TextureTransform.GLINT_TEXTURING)
                        .useLightmap()
                        .useOverlay()
                        .affectsCrumbling()
                        .sortOnUpload()
                        .setOutline(RenderSetup.OutlineProperty.AFFECTS_OUTLINE)
                        .createRenderSetup()));
    }

    // iris loads the vanilla glint texture mid-draw for inline glint, which crashes if it isn't loaded yet
    private static Identifier inlineItemTexture(DyeColor color) {
        Minecraft.getInstance().getTextureManager().getTexture(ItemFeatureRenderer.ENCHANTED_GLINT_ITEM);
        return itemTexture(color);
    }

    public static RenderType entityGlint(DyeColor color) {
        return CACHE.computeIfAbsent(new Key("entity_glint", null, color), key -> RenderType.create("entity_glint",
                RenderSetup.builder(RenderPipelines.GLINT)
                        .withTexture("Sampler0", itemTexture(color), GLINT_SAMPLER)
                        .setTextureTransform(TextureTransform.ENTITY_GLINT_TEXTURING)
                        .withForcedSolidModelPhase()
                        .createRenderSetup()));
    }

    public static RenderType armorGlint(DyeColor color) {
        return CACHE.computeIfAbsent(new Key("armor_glint", null, color), key -> RenderType.create("armor_glint",
                RenderSetup.builder(RenderPipelines.GLINT)
                        .withTexture("Sampler0", entityTexture(color), GLINT_SAMPLER)
                        .setTextureTransform(TextureTransform.ARMOR_ENTITY_GLINT_TEXTURING)
                        .setLayeringTransform(LayeringTransform.VIEW_OFFSET_Z_LAYERING)
                        .withForcedSolidModelPhase()
                        .createRenderSetup()));
    }

    private record Key(String type, @Nullable Identifier texture, DyeColor color) {
    }
}
