package one.dqu.additionaladditions.item;

import net.minecraft.core.component.DataComponentMap;
import net.minecraft.world.item.HoeItem;
import net.minecraft.world.item.ToolMaterial;
import one.dqu.additionaladditions.material.AAMaterial;
import one.dqu.additionaladditions.material.ToolType;

import java.util.function.Consumer;

public class AAHoeItem extends HoeItem {
    Consumer<DataComponentMap.Builder> configurer;

    public AAHoeItem(AAMaterial material, Properties properties) {
        // dummy values. actual values are generated by AAMaterial
        super(ToolMaterial.WOOD, 0, 0, properties.repairable(material.repairIngredient()));

        this.configurer = builder -> material.applyFor(builder, ToolType.HOE);
    }

    /**
     * @see one.dqu.additionaladditions.item.configurable.ConfigurableItem
     */
    @Override
    public DataComponentMap components() {
        DataComponentMap.Builder builder = DataComponentMap.builder().addAll(super.components());
        configurer.accept(builder);
        return builder.build();
    }
}
